const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Behaviors.Timer,
		C3.Plugins.TiledBg,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Rotate,
		C3.Plugins.InstantGamesBridge,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.InstantGamesBridge.Acts.ShowInterstitial,
		C3.Plugins.InstantGamesBridge.Acts.ShowBanner
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Sprite: 0},
	{Audio: 0},
	{Timer: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{TiledBackground: 0},
	{Button: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{TiledBackground2: 0},
	{Sine: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Variable1: 0},
	{css: 0},
	{mbutton: 0},
	{Sprite23: 0},
	{Sprite33: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{A: 0},
	{B: 0},
	{C: 0},
	{D: 0},
	{E: 0},
	{F: 0},
	{G: 0},
	{H: 0},
	{i: 0},
	{J: 0},
	{K: 0},
	{Ll: 0},
	{M: 0},
	{n: 0},
	{o: 0},
	{P: 0},
	{Q: 0},
	{r: 0},
	{S: 0},
	{T: 0},
	{u: 0},
	{v: 0},
	{Ww: 0},
	{x: 0},
	{y: 0},
	{z: 0},
	{switcheng: 0},
	{ShadowCaster: 0},
	{Text4: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{Text8: 0},
	{prevword: 0},
	{nextword: 0},
	{Text9: 0},
	{Text10: 0},
	{full: 0},
	{Sprite12: 0},
	{TiledBackground5: 0},
	{zbutton: 0},
	{toz: 0},
	{hot2play: 0},
	{TiledBackground6: 0},
	{test1: 0},
	{TiledBackground7: 0},
	{no: 0},
	{yes: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{junglebg: 0},
	{dog: 0},
	{cat: 0},
	{bear: 0},
	{wolf: 0},
	{rhinoceros: 0},
	{parrot: 0},
	{chicken: 0},
	{duck: 0},
	{elephant: 0},
	{giraffe: 0},
	{cow: 0},
	{pig: 0},
	{lion: 0},
	{tiger: 0},
	{monkey: 0},
	{zebra: 0},
	{turtle: 0},
	{Sprite43: 0},
	{snake: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{table: 0},
	{apple: 0},
	{pear: 0},
	{Rotate: 0},
	{banana: 0},
	{lemon: 0},
	{watermelon: 0},
	{orange: 0},
	{pineapple: 0},
	{garnet: 0},
	{grapes: 0},
	{kiwi: 0},
	{cucmber: 0},
	{tomato: 0},
	{corn: 0},
	{carrot: 0},
	{potato: 0},
	{cabage: 0},
	{pumpkin: 0},
	{onion: 0},
	{TiledBackground8: 0},
	{soundbutton: 0},
	{TiledBackground9: 0},
	{ruslang: 0},
	{Sprite46: 0},
	{alfavit: 0},
	{cifr: 0},
	{cveta: 0},
	{figury: 0},
	{eda: 0},
	{Sprite47: 0},
	{testy: 0},
	{Sprite48: 0},
	{cvettest: 0},
	{figtest: 0},
	{jivottest: 0},
	{edatest: 0},
	{rusmenu: 0},
	{vsebukvi: 0},
	{uchitpo1: 0},
	{nextword2: 0},
	{prevword2: 0},
	{TiledBackground10: 0},
	{loadingimg: 0},
	{zbutton2: 0},
	{TiledBackground11: 0},
	{house: 0},
	{door: 0},
	{window: 0},
	{bed: 0},
	{pillow: 0},
	{sofa: 0},
	{blanket: 0},
	{carpet: 0},
	{chair: 0},
	{armscair: 0},
	{lamp: 0},
	{mirror: 0},
	{tableimg: 0},
	{shower: 0},
	{bath: 0},
	{sink: 0},
	{toilet: 0},
	{showel: 0},
	{tree: 0},
	{flower: 0},
	{sun: 0},
	{cloud: 0},
	{star: 0},
	{halfmoon: 0},
	{moon: 0},
	{stone: 0},
	{houserusbt: 0},
	{Actionrus: 0},
	{streetrus: 0},
	{Sprite49: 0},
	{transportrus: 0},
	{thingsinhouse: 0},
	{bench: 0},
	{trafficlight: 0},
	{tv: 0},
	{vacuumcleaner: 0},
	{aircond: 0},
	{kitshenthing: 0},
	{knife: 0},
	{fork: 0},
	{spoon: 0},
	{refreg: 0},
	{microwave: 0},
	{mug: 0},
	{cup: 0},
	{glass: 0},
	{gasoven: 0},
	{taxi: 0},
	{car: 0},
	{plane: 0},
	{bus: 0},
	{helicopter: 0},
	{TiledBackground12: 0},
	{TiledBackground13: 0},
	{housebg: 0},
	{ENHOUSETHINGS: 0},
	{ENKITCHEN: 0},
	{homethingsenng: 0},
	{OUTDIFRTHINGS: 0},
	{pen: 0},
	{pencil: 0},
	{higlighter: 0},
	{TiledBackground14: 0},
	{ruler: 0},
	{scissors: 0},
	{paperclip: 0},
	{laptop: 0},
	{phone: 0},
	{phone2: 0},
	{pointer: 0},
	{blackboard: 0},
	{bagpack: 0},
	{book: 0},
	{schoolrus: 0},
	{schooleng: 0},
	{InstantGamesBridge: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	css: class extends self.IJSONInstance {},
	mbutton: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	A: class extends self.ITextInstance {},
	B: class extends self.ITextInstance {},
	C: class extends self.ITextInstance {},
	D: class extends self.ITextInstance {},
	E: class extends self.ITextInstance {},
	F: class extends self.ITextInstance {},
	G: class extends self.ITextInstance {},
	H: class extends self.ITextInstance {},
	i: class extends self.ITextInstance {},
	J: class extends self.ITextInstance {},
	K: class extends self.ITextInstance {},
	Ll: class extends self.ITextInstance {},
	M: class extends self.ITextInstance {},
	n: class extends self.ITextInstance {},
	o: class extends self.ITextInstance {},
	P: class extends self.ITextInstance {},
	Q: class extends self.ITextInstance {},
	r: class extends self.ITextInstance {},
	S: class extends self.ITextInstance {},
	T: class extends self.ITextInstance {},
	u: class extends self.ITextInstance {},
	v: class extends self.ITextInstance {},
	Ww: class extends self.ITextInstance {},
	x: class extends self.ITextInstance {},
	y: class extends self.ITextInstance {},
	z: class extends self.ITextInstance {},
	switcheng: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	prevword: class extends self.ISpriteInstance {},
	nextword: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	full: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	zbutton: class extends self.ISpriteInstance {},
	toz: class extends self.ISpriteInstance {},
	hot2play: class extends self.ITextInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	test1: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	no: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	junglebg: class extends self.ITiledBackgroundInstance {},
	dog: class extends self.ISpriteInstance {},
	cat: class extends self.ISpriteInstance {},
	bear: class extends self.ISpriteInstance {},
	wolf: class extends self.ISpriteInstance {},
	rhinoceros: class extends self.ISpriteInstance {},
	parrot: class extends self.ISpriteInstance {},
	chicken: class extends self.ISpriteInstance {},
	duck: class extends self.ISpriteInstance {},
	elephant: class extends self.ISpriteInstance {},
	giraffe: class extends self.ISpriteInstance {},
	cow: class extends self.ISpriteInstance {},
	pig: class extends self.ISpriteInstance {},
	lion: class extends self.ISpriteInstance {},
	tiger: class extends self.ISpriteInstance {},
	monkey: class extends self.ISpriteInstance {},
	zebra: class extends self.ISpriteInstance {},
	turtle: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	snake: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	table: class extends self.ITiledBackgroundInstance {},
	apple: class extends self.ISpriteInstance {},
	pear: class extends self.ISpriteInstance {},
	banana: class extends self.ISpriteInstance {},
	lemon: class extends self.ISpriteInstance {},
	watermelon: class extends self.ISpriteInstance {},
	orange: class extends self.ISpriteInstance {},
	pineapple: class extends self.ISpriteInstance {},
	garnet: class extends self.ISpriteInstance {},
	grapes: class extends self.ISpriteInstance {},
	kiwi: class extends self.ISpriteInstance {},
	cucmber: class extends self.ISpriteInstance {},
	tomato: class extends self.ISpriteInstance {},
	corn: class extends self.ISpriteInstance {},
	carrot: class extends self.ISpriteInstance {},
	potato: class extends self.ISpriteInstance {},
	cabage: class extends self.ISpriteInstance {},
	pumpkin: class extends self.ISpriteInstance {},
	onion: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	soundbutton: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	ruslang: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	alfavit: class extends self.ISpriteInstance {},
	cifr: class extends self.ISpriteInstance {},
	cveta: class extends self.ISpriteInstance {},
	figury: class extends self.ISpriteInstance {},
	eda: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	testy: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	cvettest: class extends self.ISpriteInstance {},
	figtest: class extends self.ISpriteInstance {},
	jivottest: class extends self.ISpriteInstance {},
	edatest: class extends self.ISpriteInstance {},
	rusmenu: class extends self.ISpriteInstance {},
	vsebukvi: class extends self.ISpriteInstance {},
	uchitpo1: class extends self.ISpriteInstance {},
	nextword2: class extends self.ISpriteInstance {},
	prevword2: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	loadingimg: class extends self.ISpriteInstance {},
	zbutton2: class extends self.ISpriteInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	house: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	window: class extends self.ISpriteInstance {},
	bed: class extends self.ISpriteInstance {},
	pillow: class extends self.ISpriteInstance {},
	sofa: class extends self.ISpriteInstance {},
	blanket: class extends self.ISpriteInstance {},
	carpet: class extends self.ISpriteInstance {},
	chair: class extends self.ISpriteInstance {},
	armscair: class extends self.ISpriteInstance {},
	lamp: class extends self.ISpriteInstance {},
	mirror: class extends self.ISpriteInstance {},
	tableimg: class extends self.ISpriteInstance {},
	shower: class extends self.ISpriteInstance {},
	bath: class extends self.ISpriteInstance {},
	sink: class extends self.ISpriteInstance {},
	toilet: class extends self.ISpriteInstance {},
	showel: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	flower: class extends self.ISpriteInstance {},
	sun: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	halfmoon: class extends self.ISpriteInstance {},
	moon: class extends self.ISpriteInstance {},
	stone: class extends self.ISpriteInstance {},
	houserusbt: class extends self.ISpriteInstance {},
	Actionrus: class extends self.ISpriteInstance {},
	streetrus: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	transportrus: class extends self.ISpriteInstance {},
	thingsinhouse: class extends self.ISpriteInstance {},
	bench: class extends self.ISpriteInstance {},
	trafficlight: class extends self.ISpriteInstance {},
	tv: class extends self.ISpriteInstance {},
	vacuumcleaner: class extends self.ISpriteInstance {},
	aircond: class extends self.ISpriteInstance {},
	kitshenthing: class extends self.ISpriteInstance {},
	knife: class extends self.ISpriteInstance {},
	fork: class extends self.ISpriteInstance {},
	spoon: class extends self.ISpriteInstance {},
	refreg: class extends self.ISpriteInstance {},
	microwave: class extends self.ISpriteInstance {},
	mug: class extends self.ISpriteInstance {},
	cup: class extends self.ISpriteInstance {},
	glass: class extends self.ISpriteInstance {},
	gasoven: class extends self.ISpriteInstance {},
	taxi: class extends self.ISpriteInstance {},
	car: class extends self.ISpriteInstance {},
	plane: class extends self.ISpriteInstance {},
	bus: class extends self.ISpriteInstance {},
	helicopter: class extends self.ISpriteInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	housebg: class extends self.ITiledBackgroundInstance {},
	ENHOUSETHINGS: class extends self.ISpriteInstance {},
	ENKITCHEN: class extends self.ISpriteInstance {},
	homethingsenng: class extends self.ISpriteInstance {},
	OUTDIFRTHINGS: class extends self.ISpriteInstance {},
	pen: class extends self.ISpriteInstance {},
	pencil: class extends self.ISpriteInstance {},
	higlighter: class extends self.ISpriteInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	ruler: class extends self.ISpriteInstance {},
	scissors: class extends self.ISpriteInstance {},
	paperclip: class extends self.ISpriteInstance {},
	laptop: class extends self.ISpriteInstance {},
	phone: class extends self.ISpriteInstance {},
	phone2: class extends self.ISpriteInstance {},
	pointer: class extends self.ISpriteInstance {},
	blackboard: class extends self.ISpriteInstance {},
	bagpack: class extends self.ISpriteInstance {},
	book: class extends self.ISpriteInstance {},
	schoolrus: class extends self.ISpriteInstance {},
	schooleng: class extends self.ISpriteInstance {},
	InstantGamesBridge: class extends self.IInstance {}
}